ExeRibeiroCipriano/Models/Carro.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ExeRibeiroCipriano.Models
{
    public class Carro : veiculo
    {
        public string tipo { get; set; }
        public string nome { get; set; }
    }
}

ExeRibeiroCipriano/Models/Moto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ExeRibeiroCipriano.Models
{
    public class Moto : veiculo
    {
        public int cilindrada { get; set; }
        public string categoria { get; set; }
    }
}

ExeRibeiroCipriano/Models/veiculo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ExeRibeiroCipriano.Models
{
    public class veiculo
    {

        public string chassis { get; set; }
        public string transmissao { get; set; }
        public string fabricante { get; set; }

    }
}

ExeRibeiroCipriano/Areas/Veiculo/Controllers/AutoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ExeRibeiroCipriano.Models;

namespace ExeRibeiroCipriano.Areas.Veiculo.Controllers
{
    public class AutoController : Controller
    {

        private Carro infoCarro()
        {
            return new Carro
            {
                fabricante = "Jaguar",
                tipo = "sport",
                nome = "XE",
                transmissao = "automática"
            };
        }

        private Moto infoMoto()
        {
            return new Moto
            {
                fabricante = "Kawasaki",
                categoria = "2023",
                cilindrada = 948,
                transmissao = "automática"
            };
        }

        public ActionResult Veiculos()
        {
            var carro = infoCarro();
            var moto = infoMoto();

            var tupla = new Tuple<Carro, Moto>(carro, moto);

            return View(tupla);
        }

        public ActionResult ConsultaCarros()
        {
            var carro = infoCarro();
            return View(carro);
        }

        public ActionResult ConsultaMoto()
        {
            var moto = infoMoto();
            return View(moto);
        }
    }
}

ExeRibeiroCipriano/Controllers/FuncionarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExeRibeiroCipriano.Controllers
{
    public class FuncionarioController : Controller
    {
        // GET: Funcionario
        public ActionResult Index()
        {
            return View();
        }
    }
}

ExeRibeiroCipriano/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExeRibeiroCipriano.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Inicio()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ExeRibeiroCipriano/Areas/Veiculo/Views/Auto/ConsultaCarros.cshtml
@model ExeRibeiroCipriano.Models.Carro

@{
    ViewBag.Title = "CosultaCarros";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<main class="centered">
    <h2>Carros</h2>
    <img src="~/Imagens/jaguar.jpg"/>
    <p><b>@Model.fabricante / @Model.tipo / @Model.nome / @Model.transmissao</b></p>
</main>

ExeRibeiroCipriano/Areas/Veiculo/Views/Auto/ConsultaMoto.cshtml
@model ExeRibeiroCipriano.Models.Moto

@{
    ViewBag.Title = "ConsultaMoto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<main class="centered">
    <h2>Moto</h2>
    <img src="~/Imagens/kk.jpeg" width="700" height="500"/>
    <p><b>@Model.fabricante / @Model.categoria / @Model.cilindrada cc / @Model.transmissao</b></p>
</main>

ExeRibeiroCipriano/Areas/Veiculo/Views/Auto/Veiculos.cshtml
@model Tuple<ExeRibeiroCipriano.Models.Carro, ExeRibeiroCipriano.Models.Moto>


@{
    ViewBag.Title = "Veiculos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<main class="centred">

    <h2>Veiculos</h2>
    <img src="~/Imagens/kk.jpeg" width="700" height="500" />
    <p><b>@Model.Item2.fabricante / @Model.Item2.categoria / @Model.Item2.cilindrada cc / @Model.Item2.transmissao</b></p>
    <img src="~/Imagens/jaguar.jpg" />
    <p><b>@Model.Item1.fabricante / @Model.Item1.tipo / @Model.Item1.nome / @Model.Item1.transmissao</b></p>

</main>

ExeRibeiroCipriano/Areas/Veiculo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ExeRibeiroCipriano/Views/Funcionario/Index.cshtml
@{
    Layout = null;
}

<title>Funcionário</title>

<h1>Desculpe!</h1>

<h2>Área em desenvolvimento clique em @Html.ActionLink("Retornar", "Inicio", "Home")</h2>

ExeRibeiroCipriano/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

ExeRibeiroCipriano/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

ExeRibeiroCipriano/Views/Home/Inicio.cshtml
@{
    ViewBag.Title = "Inicio";
}

<main>
    
    <h1>Página Inicial</h1>

</main>

ExeRibeiroCipriano/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Exercício III</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Início", "Inicio", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar a navegação" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Funcionário", "Index", "Funcionario", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Moto", "ConsultaMoto", "Auto", new { area = "Veiculo" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Carro", "ConsultaCarros", "Auto", new { area = "Veiculo" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Veiculos", "Veiculos", "Auto", new { area = "Veiculo" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Desenvolvedor Ribeiro Cipriano</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>